### ISSUE TITLE
Peer to peer code review 6 January 20223

### ISSUE THREAD

**Issue by rugwizangoga** [Wahaj-Ali/tv-hub#32]
HI @Wahaj-Ali and @Lucash2022

Good job implementing project requirement, You are almost there but there still some changes to be done 
 
![nice](https://user-images.githubusercontent.com/57993089/186997194-fe3ab17b-0a27-459e-bfd3-c533099dbcaf.gif)

- Clean codes
- no linter errors
- professional GitHub workflow
- professional documentation
- responsive and mobile-first designing
- Good Interactiveness by color changes

**Comment by Wahaj-Ali** [comment]
Added a descriptive readme file ✅
